//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ledbox.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_en {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_en() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ledbox.Resources.AppResources.en", typeof(AppResources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        internal static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        internal static string sure_disconnect {
            get {
                return ResourceManager.GetString("sure_disconnect", resourceCulture);
            }
        }
        
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        internal static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        internal static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        internal static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        internal static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        internal static string move_up {
            get {
                return ResourceManager.GetString("move_up", resourceCulture);
            }
        }
        
        internal static string move_down {
            get {
                return ResourceManager.GetString("move_down", resourceCulture);
            }
        }
        
        internal static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        internal static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        internal static string change_language {
            get {
                return ResourceManager.GetString("change_language", resourceCulture);
            }
        }
        
        internal static string change_user {
            get {
                return ResourceManager.GetString("change_user", resourceCulture);
            }
        }
        
        internal static string change_connection {
            get {
                return ResourceManager.GetString("change_connection", resourceCulture);
            }
        }
        
        internal static string reboot_app {
            get {
                return ResourceManager.GetString("reboot_app", resourceCulture);
            }
        }
        
        internal static string preferences {
            get {
                return ResourceManager.GetString("preferences", resourceCulture);
            }
        }
        
        internal static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        internal static string select_connection {
            get {
                return ResourceManager.GetString("select_connection", resourceCulture);
            }
        }
        
        internal static string playlist {
            get {
                return ResourceManager.GetString("playlist", resourceCulture);
            }
        }
        
        internal static string match_score {
            get {
                return ResourceManager.GetString("match_score", resourceCulture);
            }
        }
        
        internal static string practice {
            get {
                return ResourceManager.GetString("practice", resourceCulture);
            }
        }
        
        internal static string weight_gym {
            get {
                return ResourceManager.GetString("weight_gym", resourceCulture);
            }
        }
        
        internal static string custom_text {
            get {
                return ResourceManager.GetString("custom_text", resourceCulture);
            }
        }
        
        internal static string create_playlist {
            get {
                return ResourceManager.GetString("create_playlist", resourceCulture);
            }
        }
        
        internal static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        internal static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        internal static string image_video {
            get {
                return ResourceManager.GetString("image_video", resourceCulture);
            }
        }
        
        internal static string audio {
            get {
                return ResourceManager.GetString("audio", resourceCulture);
            }
        }
        
        internal static string insert_title {
            get {
                return ResourceManager.GetString("insert_title", resourceCulture);
            }
        }
        
        internal static string error_connecting {
            get {
                return ResourceManager.GetString("error_connecting", resourceCulture);
            }
        }

        internal static string reset
        {
            get
            {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
    }
}
