//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ledbox.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ledbox.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a INFORMAZIONI.
        /// </summary>
        public static string about_us {
            get {
                return ResourceManager.GetString("about_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Non è possibile utilizzare questa interfaccia perchè il LEDbox è già controllato da un altro utente..
        /// </summary>
        public static string access_denied {
            get {
                return ResourceManager.GetString("access_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona comando:.
        /// </summary>
        public static string action {
            get {
                return ResourceManager.GetString("action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ATTIVITA&apos;.
        /// </summary>
        public static string activity {
            get {
                return ResourceManager.GetString("activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ci sono attività in corso sul LEDbox. Visualizzarle?.
        /// </summary>
        public static string activitydialog {
            get {
                return ResourceManager.GetString("activitydialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Funzioni avanzate LEDbox.
        /// </summary>
        public static string advanced_function_ledbox {
            get {
                return ResourceManager.GetString("advanced_function_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Animazione.
        /// </summary>
        public static string animation {
            get {
                return ResourceManager.GetString("animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Velocità.
        /// </summary>
        public static string animation_velocity {
            get {
                return ResourceManager.GetString("animation_velocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Un altro processo è già in esecuzione sul LEDbox..
        /// </summary>
        public static string another_diplay_process_execute {
            get {
                return ResourceManager.GetString("another_diplay_process_execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La versione dell&apos;app non è compatibile con questo LEDbox. Aggiornare l&apos;app all&apos;ultima versione disponibile..
        /// </summary>
        public static string app_not_compatible {
            get {
                return ResourceManager.GetString("app_not_compatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sicuro di voler continuare con l&apos;operazione?.
        /// </summary>
        public static string are_you_sure {
            get {
                return ResourceManager.GetString("are_you_sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Audio.
        /// </summary>
        public static string audio {
            get {
                return ResourceManager.GetString("audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lampeggiante.
        /// </summary>
        public static string blinking {
            get {
                return ResourceManager.GetString("blinking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Blu.
        /// </summary>
        public static string blue {
            get {
                return ResourceManager.GetString("blue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Annulla.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipo connessione.
        /// </summary>
        public static string change_connection {
            get {
                return ResourceManager.GetString("change_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lingua.
        /// </summary>
        public static string change_language {
            get {
                return ResourceManager.GetString("change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cambia utente.
        /// </summary>
        public static string change_user {
            get {
                return ResourceManager.GetString("change_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scarica aggiornamento LEDbox.
        /// </summary>
        public static string check_last_ledbox_version {
            get {
                return ResourceManager.GetString("check_last_ledbox_version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scegli.
        /// </summary>
        public static string choose {
            get {
                return ResourceManager.GetString("choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona il LEDbox a cui collegarti.
        /// </summary>
        public static string choose_bluetooth {
            get {
                return ResourceManager.GetString("choose_bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Colore.
        /// </summary>
        public static string color_text {
            get {
                return ResourceManager.GetString("color_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Configurazioni salvate.
        /// </summary>
        public static string config_saved {
            get {
                return ResourceManager.GetString("config_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Configura LEDbox.
        /// </summary>
        public static string configure_ledbox {
            get {
                return ResourceManager.GetString("configure_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a File eliminati correttamente sul LEDbox..
        /// </summary>
        public static string confirm_deletion {
            get {
                return ResourceManager.GetString("confirm_deletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disinstallare l&apos;elemento selezionato?.
        /// </summary>
        public static string confirm_disinstallation {
            get {
                return ResourceManager.GetString("confirm_disinstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scaricare ed installare l&apos;elemento selezionato?.
        /// </summary>
        public static string confirm_installation {
            get {
                return ResourceManager.GetString("confirm_installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connetti.
        /// </summary>
        public static string connect {
            get {
                return ResourceManager.GetString("connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Avviare la connessione all&apos;ultimo LEDbox a cui ti sei collegato?.
        /// </summary>
        public static string connect_last_ledbox {
            get {
                return ResourceManager.GetString("connect_last_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Collegare il device alla rete Wi-Fi in cui è collegato il LEDbox..
        /// </summary>
        public static string connect_to_wifi {
            get {
                return ResourceManager.GetString("connect_to_wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Prima effettuare la connessione al LEDbox..
        /// </summary>
        public static string connecting_before_ledbox {
            get {
                return ResourceManager.GetString("connecting_before_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connessione a LEDbox in corso ....
        /// </summary>
        public static string connecting_ledbox {
            get {
                return ResourceManager.GetString("connecting_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Crea playlist.
        /// </summary>
        public static string create_playlist {
            get {
                return ResourceManager.GetString("create_playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Creazione del file in corso....
        /// </summary>
        public static string creation_progress {
            get {
                return ResourceManager.GetString("creation_progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Informazioni su....
        /// </summary>
        public static string credits {
            get {
                return ResourceManager.GetString("credits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impostazione corrente: .
        /// </summary>
        public static string current_setting {
            get {
                return ResourceManager.GetString("current_setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TESTO LIBERO.
        /// </summary>
        public static string custom_text {
            get {
                return ResourceManager.GetString("custom_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elimina.
        /// </summary>
        public static string delete {
            get {
                return ResourceManager.GetString("delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elimina tutte le playlist audio sul LEDbox.
        /// </summary>
        public static string delete_playlistaudio {
            get {
                return ResourceManager.GetString("delete_playlistaudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elimina tutte le sequenze di esercizi sul LEDbox.
        /// </summary>
        public static string delete_playlistimage {
            get {
                return ResourceManager.GetString("delete_playlistimage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rete LAN riavviata.
        /// </summary>
        public static string dhcp_restarted {
            get {
                return ResourceManager.GetString("dhcp_restarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Per connettersi in Wi-Fi al LEDbox disabilitare i Dati mobili del dispositivo..
        /// </summary>
        public static string disable_mobile_connection {
            get {
                return ResourceManager.GetString("disable_mobile_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disconnetti.
        /// </summary>
        public static string disconnect {
            get {
                return ResourceManager.GetString("disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Per cambiare la lingua ho disconnesso il LEDbox..
        /// </summary>
        public static string disconnect_for_change_language {
            get {
                return ResourceManager.GetString("disconnect_for_change_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disinstallazione.
        /// </summary>
        public static string disinstallation {
            get {
                return ResourceManager.GetString("disinstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scarica ed installa.
        /// </summary>
        public static string download_and_install {
            get {
                return ResourceManager.GetString("download_and_install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggiornamento LEDbox scaricato correttamente..
        /// </summary>
        public static string download_last_upgrade_completed {
            get {
                return ResourceManager.GetString("download_last_upgrade_completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scaricamento lista in corso....
        /// </summary>
        public static string download_list {
            get {
                return ResourceManager.GetString("download_list", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scarica manuale.
        /// </summary>
        public static string download_manual {
            get {
                return ResourceManager.GetString("download_manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scaricamento in corso....
        /// </summary>
        public static string downloading {
            get {
                return ResourceManager.GetString("downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scaricamento dati di default in corso....
        /// </summary>
        public static string downloading_preinstall {
            get {
                return ResourceManager.GetString("downloading_preinstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Duplica.
        /// </summary>
        public static string duplicate {
            get {
                return ResourceManager.GetString("duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modifica.
        /// </summary>
        public static string edit {
            get {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a elementi.
        /// </summary>
        public static string elements {
            get {
                return ResourceManager.GetString("elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserisci l&apos;indirizzo IP del LEDbox (prova con 172.24.1.1) e riprova a connetterti..
        /// </summary>
        public static string enter_ip_ledbox {
            get {
                return ResourceManager.GetString("enter_ip_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore di comunicazione con il LEDbox.
        /// </summary>
        public static string error_communication {
            get {
                return ResourceManager.GetString("error_communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante la connessione.
        /// </summary>
        public static string error_connection {
            get {
                return ResourceManager.GetString("error_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante la connessione a LEDbox.
        /// </summary>
        public static string error_connection_to_ledbox {
            get {
                return ResourceManager.GetString("error_connection_to_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante la connessione Bluetooth. Verificare che il LEDbox sia acceso..
        /// </summary>
        public static string error_connection_to_ledbox_bluetooth {
            get {
                return ResourceManager.GetString("error_connection_to_ledbox_bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore durante lo scaricamento.
        /// </summary>
        public static string error_download {
            get {
                return ResourceManager.GetString("error_download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore nella creazione dell&apos;immagine.
        /// </summary>
        public static string error_image {
            get {
                return ResourceManager.GetString("error_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore di lettura.
        /// </summary>
        public static string error_read {
            get {
                return ResourceManager.GetString("error_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore nel caricamento sul LEDbox..
        /// </summary>
        public static string error_upload {
            get {
                return ResourceManager.GetString("error_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Errore nella creazione del pacchetto dei file multimediali..
        /// </summary>
        public static string error_zip {
            get {
                return ResourceManager.GetString("error_zip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dal tuo dispositivo.
        /// </summary>
        public static string from_local {
            get {
                return ResourceManager.GetString("from_local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Online.
        /// </summary>
        public static string from_online {
            get {
                return ResourceManager.GetString("from_online", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Galleria.
        /// </summary>
        public static string gallery {
            get {
                return ResourceManager.GetString("gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Verde.
        /// </summary>
        public static string green {
            get {
                return ResourceManager.GetString("green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Immagini.
        /// </summary>
        public static string image {
            get {
                return ResourceManager.GetString("image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Copertina sul LEDbox.
        /// </summary>
        public static string image_cover {
            get {
                return ResourceManager.GetString("image_cover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Immagini.
        /// </summary>
        public static string image_video {
            get {
                return ResourceManager.GetString("image_video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Copertina.
        /// </summary>
        public static string image_wait {
            get {
                return ResourceManager.GetString("image_wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserisci il nome della playlist.
        /// </summary>
        public static string insert_name_playlist {
            get {
                return ResourceManager.GetString("insert_name_playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserisci il nome della sequenza di esercizi.
        /// </summary>
        public static string insert_name_practice {
            get {
                return ResourceManager.GetString("insert_name_practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserisci il titolo.
        /// </summary>
        public static string insert_title {
            get {
                return ResourceManager.GetString("insert_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Installazione.
        /// </summary>
        public static string installation {
            get {
                return ResourceManager.GetString("installation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Installazione completata.
        /// </summary>
        public static string installation_complete {
            get {
                return ResourceManager.GetString("installation_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Questa interfaccia può essere utilizzata solo dal primo utente che si è connesso sul LEDbox..
        /// </summary>
        public static string interface_for_only_admin {
            get {
                return ResourceManager.GetString("interface_for_only_admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Questa interfaccia può essere utilizzata solo con connessioni Bluetooth..
        /// </summary>
        public static string interface_for_only_bluetooth_connection {
            get {
                return ResourceManager.GetString("interface_for_only_bluetooth_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Questa interfaccia può essere utilizzata solo con connessioni Wi-Fi..
        /// </summary>
        public static string interface_for_only_wifi_connection {
            get {
                return ResourceManager.GetString("interface_for_only_wifi_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a È presente un&apos;interfaccia più vecchia di quella che si sta installando. Disinstallare la vecchia interfaccia?.
        /// </summary>
        public static string interface_yet_present {
            get {
                return ResourceManager.GetString("interface_yet_present", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo IP (LAN).
        /// </summary>
        public static string ip_lan {
            get {
                return ResourceManager.GetString("ip_lan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo IP (Wifi).
        /// </summary>
        public static string ip_wifi {
            get {
                return ResourceManager.GetString("ip_wifi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Questo elemento è presente solo sul LEDbox. È possibile solo avviare / mettere in pausa / interropere l&apos;esecuzione..
        /// </summary>
        public static string item_only_on_ledbox {
            get {
                return ResourceManager.GetString("item_only_on_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LEDbox connesso correttamente..
        /// </summary>
        public static string ledbox_connected {
            get {
                return ResourceManager.GetString("ledbox_connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Funzionalità LEDbox.
        /// </summary>
        public static string ledbox_functions {
            get {
                return ResourceManager.GetString("ledbox_functions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun LEDbox trovato..
        /// </summary>
        public static string ledbox_not_found {
            get {
                return ResourceManager.GetString("ledbox_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ricerca del LEDbox in corso....
        /// </summary>
        public static string ledbox_search {
            get {
                return ResourceManager.GetString("ledbox_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sto riavviando il LEDbox per completare l&apos;aggiornamento..
        /// </summary>
        public static string ledbox_updated {
            get {
                return ResourceManager.GetString("ledbox_updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessuna sequenza di esercizi presente sul LEDbox corrente..
        /// </summary>
        public static string list_empty_practice_remote {
            get {
                return ResourceManager.GetString("list_empty_practice_remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Caricamento in corso ....
        /// </summary>
        public static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ciao, inserisci qui i tuoi dati poi premi su OK..
        /// </summary>
        public static string login_intro {
            get {
                return ResourceManager.GetString("login_intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a suono lungo.
        /// </summary>
        public static string long_beep {
            get {
                return ResourceManager.GetString("long_beep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a suoni lunghi.
        /// </summary>
        public static string long_beeps {
            get {
                return ResourceManager.GetString("long_beeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo IP (master) non valido.
        /// </summary>
        public static string master_ip_not_valid {
            get {
                return ResourceManager.GetString("master_ip_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a SEGNAPUNTI.
        /// </summary>
        public static string match_score {
            get {
                return ResourceManager.GetString("match_score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Memoria LEDbox.
        /// </summary>
        public static string memory_ledbox {
            get {
                return ResourceManager.GetString("memory_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Comando inviato al LEDbox.
        /// </summary>
        public static string message_sended {
            get {
                return ResourceManager.GetString("message_sended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ruolo nella comunicazione.
        /// </summary>
        public static string mode_execute {
            get {
                return ResourceManager.GetString("mode_execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modalità display.
        /// </summary>
        public static string modifier_layout {
            get {
                return ResourceManager.GetString("modifier_layout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sposta giù.
        /// </summary>
        public static string move_down {
            get {
                return ResourceManager.GetString("move_down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sposta su.
        /// </summary>
        public static string move_up {
            get {
                return ResourceManager.GetString("move_up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a E&apos; necessario abilitare la Geolocalizzazione per la connessione WiFi..
        /// </summary>
        public static string must_enabled_location {
            get {
                return ResourceManager.GetString("must_enabled_location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo IP gateway (sezione Network) non valido..
        /// </summary>
        public static string network_gateway_not_valid {
            get {
                return ResourceManager.GetString("network_gateway_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo IP (sezione Network) non valido..
        /// </summary>
        public static string network_ip_not_valid {
            get {
                return ResourceManager.GetString("network_ip_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modalità di collegamento LAN.
        /// </summary>
        public static string network_modality {
            get {
                return ResourceManager.GetString("network_modality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo Subnet (sezione Network) non valido.
        /// </summary>
        public static string network_subnet_not_valid {
            get {
                return ResourceManager.GetString("network_subnet_not_valid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nuovo versione firmware del LEDbox scaricato..
        /// </summary>
        public static string new_firmware_ledbox_downloaded {
            get {
                return ResourceManager.GetString("new_firmware_ledbox_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a NO.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun LEDbox trovato..
        /// </summary>
        public static string no_device_bluetooth {
            get {
                return ResourceManager.GetString("no_device_bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun elemento inserito nella lista..
        /// </summary>
        public static string no_elements {
            get {
                return ResourceManager.GetString("no_elements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connessione ad internet assente..
        /// </summary>
        public static string no_internet {
            get {
                return ResourceManager.GetString("no_internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Devi disattivare la connessione Wifi del LEDbox e collegarti ad una rete internet (Wifi o mobile) per accedere ai contenuti online.
        /// </summary>
        public static string no_internet_wifi_direct {
            get {
                return ResourceManager.GetString("no_internet_wifi_direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a La versione del software del LEDbox non è compatibile con questa App..
        /// </summary>
        public static string no_ledbox_compatible {
            get {
                return ResourceManager.GetString("no_ledbox_compatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connettiti ad un LEDbox per accedere alla sua sequenza di esercizi..
        /// </summary>
        public static string no_ledbox_connect_to_practice_remote {
            get {
                return ResourceManager.GetString("no_ledbox_connect_to_practice_remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a nessuno.
        /// </summary>
        public static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun file inserito nella playlist..
        /// </summary>
        public static string none_playlist_item {
            get {
                return ResourceManager.GetString("none_playlist_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nessun esercizio inserito nella sequenza..
        /// </summary>
        public static string none_practice_item {
            get {
                return ResourceManager.GetString("none_practice_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ok.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Solo sul LEDbox.
        /// </summary>
        public static string on_ledbox {
            get {
                return ResourceManager.GetString("on_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a È disponibile un nuovo aggiornamento per LEDbox. Scaricarlo ora?.
        /// </summary>
        public static string online_new_upgrade_ledbox {
            get {
                return ResourceManager.GetString("online_new_upgrade_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mostra i parametri.
        /// </summary>
        public static string open_layout_parameters {
            get {
                return ResourceManager.GetString("open_layout_parameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Mostra copertina.
        /// </summary>
        public static string open_layout_waiting {
            get {
                return ResourceManager.GetString("open_layout_waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a LEDbox Store.
        /// </summary>
        public static string open_store {
            get {
                return ResourceManager.GetString("open_store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Arancione.
        /// </summary>
        public static string orange {
            get {
                return ResourceManager.GetString("orange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a pausa.
        /// </summary>
        public static string pause {
            get {
                return ResourceManager.GetString("pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a avvia.
        /// </summary>
        public static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PLAYLIST.
        /// </summary>
        public static string playlist {
            get {
                return ResourceManager.GetString("playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PLAYLIST (Audio).
        /// </summary>
        public static string playlist_audio {
            get {
                return ResourceManager.GetString("playlist_audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a PLAYLIST (Immagini).
        /// </summary>
        public static string playlist_imagevideo {
            get {
                return ResourceManager.GetString("playlist_imagevideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ESERCIZI.
        /// </summary>
        public static string practice {
            get {
                return ResourceManager.GetString("practice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Preferenze.
        /// </summary>
        public static string preferences {
            get {
                return ResourceManager.GetString("preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esercizi liberi.
        /// </summary>
        public static string preset {
            get {
                return ResourceManager.GetString("preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Anteprima.
        /// </summary>
        public static string preview {
            get {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Viola.
        /// </summary>
        public static string purple {
            get {
                return ResourceManager.GetString("purple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Riavvia LEDBox.
        /// </summary>
        public static string reboot {
            get {
                return ResourceManager.GetString("reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Per rendere effettive le modifiche riavviare il LEDbox. Riavviarlo ora?.
        /// </summary>
        public static string reboot_app {
            get {
                return ResourceManager.GetString("reboot_app", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Riavvio del LEDbox in corso ....
        /// </summary>
        public static string rebooting {
            get {
                return ResourceManager.GetString("rebooting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Rosso.
        /// </summary>
        public static string red {
            get {
                return ResourceManager.GetString("red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Azzera.
        /// </summary>
        public static string reset {
            get {
                return ResourceManager.GetString("reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Riavvia rete LAN.
        /// </summary>
        public static string restart_dhcp {
            get {
                return ResourceManager.GetString("restart_dhcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Avviare ora l&apos;aggiornamento del LEDbox?.
        /// </summary>
        public static string run_update {
            get {
                return ResourceManager.GetString("run_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salva.
        /// </summary>
        public static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scorrimento (da sotto verso sopra).
        /// </summary>
        public static string scroller_bottom_top {
            get {
                return ResourceManager.GetString("scroller_bottom_top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scorrimento (da sinistra verso destra).
        /// </summary>
        public static string scroller_left_right {
            get {
                return ResourceManager.GetString("scroller_left_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scorrimento (da destra verso sinistra).
        /// </summary>
        public static string scroller_right_left {
            get {
                return ResourceManager.GetString("scroller_right_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Scorrimento (da sopra verso sotto).
        /// </summary>
        public static string scroller_top_bottom {
            get {
                return ResourceManager.GetString("scroller_top_bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cercare altri LEDbox nella rete?.
        /// </summary>
        public static string search_other_ledbox {
            get {
                return ResourceManager.GetString("search_other_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ricerca....
        /// </summary>
        public static string searching {
            get {
                return ResourceManager.GetString("searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cerca LEDbox.
        /// </summary>
        public static string searching_bluetooth {
            get {
                return ResourceManager.GetString("searching_bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona la connessione al LEDbox.
        /// </summary>
        public static string select_connection {
            get {
                return ResourceManager.GetString("select_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona la lingua.
        /// </summary>
        public static string select_language {
            get {
                return ResourceManager.GetString("select_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a CONFIGURAZIONE.
        /// </summary>
        public static string setting {
            get {
                return ResourceManager.GetString("setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impostazioni.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impostazioni LEDbox.
        /// </summary>
        public static string settings_ledbox {
            get {
                return ResourceManager.GetString("settings_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a suono breve.
        /// </summary>
        public static string short_beep {
            get {
                return ResourceManager.GetString("short_beep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a suoni brevi.
        /// </summary>
        public static string short_beeps {
            get {
                return ResourceManager.GetString("short_beeps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dimensione.
        /// </summary>
        public static string size_text {
            get {
                return ResourceManager.GetString("size_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Selezionare uno sport.
        /// </summary>
        public static string sport_required {
            get {
                return ResourceManager.GetString("sport_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Riavvia rete LAN in corso ....
        /// </summary>
        public static string start_dhcp_restart {
            get {
                return ResourceManager.GetString("start_dhcp_restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a stop.
        /// </summary>
        public static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a STORE.
        /// </summary>
        public static string store {
            get {
                return ResourceManager.GetString("store", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Connessione effettuata correttamente..
        /// </summary>
        public static string success_connection {
            get {
                return ResourceManager.GetString("success_connection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sicuro di voler disconnettersi dal LEDbox?.
        /// </summary>
        public static string sure_disconnect {
            get {
                return ResourceManager.GetString("sure_disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Testo.
        /// </summary>
        public static string text {
            get {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Visibilità.
        /// </summary>
        public static string time_visibility {
            get {
                return ResourceManager.GetString("time_visibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elimina.
        /// </summary>
        public static string trash {
            get {
                return ResourceManager.GetString("trash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a TUTTI I FILE MULTIMEDIALI.
        /// </summary>
        public static string trash_all_media {
            get {
                return ResourceManager.GetString("trash_all_media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Aggiornamento LEDbox.
        /// </summary>
        public static string update_ledbox {
            get {
                return ResourceManager.GetString("update_ledbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reinstalla aggionamento .
        /// </summary>
        public static string update_to {
            get {
                return ResourceManager.GetString("update_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Premi l&apos;icona con il + per aggiungere un nuovo elemento..
        /// </summary>
        public static string use_plus_button {
            get {
                return ResourceManager.GetString("use_plus_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Premi l&apos;icona store per scaricare un nuovo segnapunti..
        /// </summary>
        public static string use_store_button {
            get {
                return ResourceManager.GetString("use_store_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome utente.
        /// </summary>
        public static string username {
            get {
                return ResourceManager.GetString("username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome utente obbligatorio.
        /// </summary>
        public static string username_required {
            get {
                return ResourceManager.GetString("username_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Versione.
        /// </summary>
        public static string version {
            get {
                return ResourceManager.GetString("version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Video.
        /// </summary>
        public static string video {
            get {
                return ResourceManager.GetString("video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attenzione.
        /// </summary>
        public static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a ATTENZIONE: ll LEDbox deve essere acceso da non più di un minuto..
        /// </summary>
        public static string warning_scan_bluetooth {
            get {
                return ResourceManager.GetString("warning_scan_bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ginnastica.
        /// </summary>
        public static string weight_gym {
            get {
                return ResourceManager.GetString("weight_gym", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Bianco.
        /// </summary>
        public static string white {
            get {
                return ResourceManager.GetString("white", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modalità di collegamento Wi-Fi.
        /// </summary>
        public static string wifi_modality {
            get {
                return ResourceManager.GetString("wifi_modality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a verranno scaricati.
        /// </summary>
        public static string will_be_downloaded {
            get {
                return ResourceManager.GetString("will_be_downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Giallo.
        /// </summary>
        public static string yellow {
            get {
                return ResourceManager.GetString("yellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Si.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hai scaricato l&apos;ultima versione di aggiornamento del LEDbox..
        /// </summary>
        public static string you_download_last_ledbox_upgrade {
            get {
                return ResourceManager.GetString("you_download_last_ledbox_upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Hai già l&apos;ultima versione di aggiornamento del LEDbox..
        /// </summary>
        public static string you_have_last_ledbox_upgrade {
            get {
                return ResourceManager.GetString("you_have_last_ledbox_upgrade", resourceCulture);
            }
        }
    }
}
